---
  - name: 加入kubernetes 集群
    command: "{{ hostvars[groups.k8s_master_first[0]]['kubernetes_join_token'] }} --control-plane"
    ignore_errors: true

  - block:
    - file: "path=/root/.kube state=directory"
    - name: 权限认证
      copy: src=/etc/kubernetes/admin.conf dest=/root/.kube/config

  - name: s.1查看节点信息
    shell: 'kubectl get nodes'
    register: check

  - name: s.2查看节点信息
    debug: var=check.stdout verbosity=0
