---
- name: 复制Nginx配置文件
  template:
    src: k8s.conf
    dest: /etc/nginx/nginx.conf

- name: Nginx配置
  service: name=nginx state=restarted

- name: 生成集群
  shell: kubeadm init --config /root/kubeadm-config.yaml
  register: check

- name: 检出集群生成信息
  debug: var=check.stdout verbosity=0 

- name: kubectl 配置文件复制
  copy:
    src: /etc/kubernetes/admin.conf 
    dest: /root/.kube/config

- name: Flannel网络插件
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml warn=False
  ignore_errors: yes
  when: flannel_install == 1

- name: 设置kubectl自动补全
  lineinfile:
    dest: ~/.bashrc
    line: "source <(kubectl completion bash)"
