---
- name: 复制Nginx配置文件
  template:
    src: k8s.conf
    dest: /etc/nginx/nginx.conf

- name: Nginx配置
  service: name=nginx state=restarted

- name: 获取join-command脚本
  copy:
    src: /tmp/join-cluster-token-master.sh
    dest: "/tmp/{{ item }}"
    group: root
    owner: root
    mode: 755
  with_items:
    - join-cluster-token-master.sh

- name: ==Master节点加入集群==
  shell: "sh /tmp/join-cluster-token-master.sh"

- name: work dir
  file: path=/root/.kube state=directory

- name: 权限认证
  copy: src=/etc/kubernetes/admin.conf dest=/root/.kube/config

- name: s.1查看节点信息
  shell: 'kubectl get nodes'
  register: check

- name: s.2查看节点信息
  debug: var=check.stdout verbosity=0
