---
- name: 接入API-Server
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes

- name: 保存Join-Cluster-Token
  copy: 
    src: /tmp/join-cluster-token-work.sh
    dest: "/tmp/{{ item }}"
    group: root
    owner: root
    mode: 755
  with_items:
    - join-cluster-token-work.sh
  
- name: ==Work节点加入集群==
  shell: "sh /tmp/join-cluster-token-work.sh"
