#ansible-playbook -i host -e @inventory/var -f 3 
---
#所有要装nginx docker kubeadm kubectl kubelet的节点

- name: "3.密钥分发distribution"
  gather_facts:  false
  hosts: k8s_master_second
  roles:
    - { role: distribution, tags: distribution }

- name: "4.保存Token"
  hosts: k8s_master_first
  roles:
    - { role: token, tags: token }

- name: "5.加入第二、三个控制节点"
  hosts: k8s_master_second
  roles:
    - { role: master_02, tags: master_02 }

- name: "6.加入计算节点"
  gather_facts:  false
  hosts: k8s_node
  roles:
    - { role: node, tags: node }
