---
- name: 添加 Kubernetes Yum源
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
    enabled: true
    gpgkey: https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
    gpgcheck: true
    state: present

- name: 安装 Kubernetes 组件
  yum: name='{{item}}' state=present
  loop:
    - "kubelet-{{version}}"
    - "kubectl-{{version}}"
    - "kubeadm-{{version}}"
  

- block:
  - copy: src="files/kubelet" dest="{{ kubelet_config_path }}/kubelet"
  - copy: src="files/10-kubeadm.conf" dest="/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
  - shell: kubeadm reset -f 
  - service: enable=true name={{ item  }}
    loop:
      - kubelet
      - nginx

- name: Create kubeadm-config Directory
  file:
     path: '/root/.kube'
     state: directory

- name: 修改内核参数
  copy:
    src: "files/k8s.conf"
    dest: "/etc/sysctl.d/k8s.conf"

- name: 重载参数
  shell: sysctl --system warn=False

- name: 生成配置文件
  template:
    src: kubeadm-config.yaml
    dest: "/root/kubeadm-config.yaml"

- block: 
  - name: Dir Create
    file: path='/etc/kubernetes/pki/etcd' state=directory
  - shell: "iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
